name          'jantman-archlinux-workstation'
version       '0.1.0'
source        'UNKNOWN'
author        'jantman'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
