name          'jantman-archlinux_workstation'
version       '0.0.1'
source        'https://github.com/jantman/puppet-archlinux-workstation'
author        'jantman'
license       'Apache License, Version 2.0'
summary       'Configure an Arch Linux workstation/desktop/laptop'
description   'Provides many classes (and a sane default class/init.pp) for configuring an Arch Linux workstation/laptop/desktop for graphical use.'
project_page  'https://github.com/jantman/puppet-archlinux-workstation'

dependency 'puppetlabs/stdlib', '>=4.1.0 <5.0.0'
dependency 'saz/sudo', '>=3.0.3, <4.0.0'
dependency 'saz/ssh', '>=2.3.3, <3.0.0'
dependency 'puppetlabs/firewall', '>=1.0.2 <2.0.0'
dependency 'puppetlabs/inifile', '>=1.0.3 <2.0.0'
